export { default as HomeScreen } from './HomeScreen'
export { default as FunctionsScreen } from './FunctionsScreen'
export { default as SettingsScreen } from './SettingsScreen'
export { default as InfoScreen } from './InfoScreen'
export { default as AboutScreen } from './AboutScreen'
